version: "3.1"

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/data/jsco

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    environment:
      ADMINER_DESIGN: mvt

volumes:
  jsco:
